version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeger-example

  go-client:
    container_name: go-client
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    ports:
      - "8080:8080"
    environment:
    # these are the default values, you can override them here.
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger
    networks:
      - jaeger-example

  go-server:
    container_name: go-server
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - LOGIN_URL=http://go-client:8080/login
      - REGISTER_URL=http://go-client:8080/register
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
    networks:
      - jaeger-example

networks:
  jaeger-example:
